### ISSUE TITLE
When no content in featured footer or story, shows an empty block

### ISSUE THREAD

**Issue by flora8984461** [EclipseFdn/jquery-eclipsefdn-api#31]
This is not very often happening, but just in case if there is no content provided at current time, the live sites are not showing weird empty space,

I think we can hide the featured footer or story or add a default content? 

@chrisguindon  Actually, I think it's good to add a default content to show in all sites, since mostly the featured story has the right logo to show, we don't want to hide them.

![image](https://user-images.githubusercontent.com/39588094/97007590-a6ad4c80-150f-11eb-8c31-c8649e9e88a4.png)
![image](https://user-images.githubusercontent.com/39588094/97007620-ad3bc400-150f-11eb-8b19-0b8285903a7c.png)

**Comment by chrisguindon** [comment]
> I think we can hide the featured footer or story or add a default content?

I think we need to discuss the featured footer and features story separately. 

### Featured Story
I am not convinced that should hide the featured story since we often have ads and important content on the right side. I think we need to figure out a way to display some default text there.

@jph152 Do you have any ideas on what content we should display if a website does not have any featured story to display? 

I am thinking that we could promote events.eclipse.org if we don't have any content to display..

### Featured Footer
This section does not have content on the right like the featured story. I think it would be reasonable to hide the section if we don't have any content.

**Comment by jph152** [comment]
@chrisguindon promoting the events page seems like the best idea since it's evergreen. I added a featured footer that promotes events.eclipse.org to replace our EclipseCon footers, so we can use that content for this as well.

**Comment by chrisguindon** [comment]
@jph152 From our side, we will add the following story as a default in our code:

Subject: ECLIPSE FOUNDATION EVENTS
Content: Join the world’s leading technologists and open source leaders at Eclipse Foundation events to share ideas, learn and collaborate.

CTA: Views Events: https://events.eclipse.org

The idea would be to display that information if the API does not return any valid stories.

@flora8984461 Let's discuss if you have any questions!

**Comment by jph152** [comment]
@chrisguindon The CTA should be "View Events" but otherwise looks good

**Comment by flora8984461** [comment]
@chrisguindon Do you mean I add a featured story in newsroom for all sites? Or you wanna add it to the js code? 
And for the footer, I will modify the code to hide the footer when no footers?

**Comment by chrisguindon** [comment]
@flora8984461 I think we decided to keep these sections there at all times.

The idea would be to hardcode the content in the plugin. The idea would be to use this hardcoded story if the API does not return any data or if it's unavailable.

**Comment by flora8984461** [comment]
> @flora8984461 I think we decided to keep these sections there at all times.
> 
> The idea would be to hardcode the content in the plugin. The idea would be to use this hardcoded story if the API does not return any data or if it's unavailable.

https://github.com/EclipseFdn/jquery-eclipsefdn-api/pull/32 Created a patch here.
